export const IPC_CHANNELS = {
  windowMinimize: 'window:minimize',
  windowToggleMaximize: 'window:toggle-maximize',
  windowClose: 'window:close',
  windowMaximizeChanged: 'window:maximize-changed',
  themeGet: 'theme:get',
  themeSet: 'theme:set',
  themeChanged: 'theme:changed',
  libraryList: 'library:list',
  libraryCreate: 'library:create',
  libraryLoad: 'library:load',
  librarySave: 'library:save',
  libraryRename: 'library:rename',
  libraryRemove: 'library:remove',
  librarySetFolder: 'library:set-folder',
  libraryThumbnail: 'library:thumbnail',
  libraryExportFile: 'library:export-file',
  libraryExportImage: 'library:export-image',
  libraryImportFile: 'library:import-file',
  libraryOpenBoard: 'library:open-board',
  foldersList: 'folders:list',
  foldersCreate: 'folders:create',
  foldersRename: 'folders:rename',
  foldersRemove: 'folders:remove',
  settingsGet: 'settings:get',
  settingsPatch: 'settings:patch',
  clipboardWriteImage: 'clipboard:write-image',
  clipboardReadImage: 'clipboard:read-image',
  appVersion: 'app:version',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
